
-- MySQL Script generated by MySQL Workbench
-- Thu Sep  7 15:12:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cofre
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cofre
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cofre` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `cofre` ;

-- -----------------------------------------------------
-- Table `cofre`.`conectividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cofre`.`conectividade` (
                                                       `idConectividade` INT NOT NULL AUTO_INCREMENT,
                                                       `protocolo` VARCHAR(45) NOT NULL,
    `porta` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`idConectividade`))
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cofre`.`fabricante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cofre`.`fabricante` (
                                                    `idFabricante` INT NOT NULL,
                                                    `nome` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`idFabricante`))
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cofre`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cofre`.`modelo` (
                                                `idModelo` INT NOT NULL AUTO_INCREMENT,
                                                `nome` VARCHAR(45) NOT NULL,
    `tipo` VARCHAR(45) NOT NULL,
    `idFabricante` INT NOT NULL,
    PRIMARY KEY (`idModelo`),
    CONSTRAINT `FK_MODELO_FABRICANTE`
    FOREIGN KEY (`idFabricante`)
    REFERENCES `cofre`.`fabricante` (`idFabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cofre`.`dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cofre`.`dispositivo` (
                                                     `idDispositivo` INT NOT NULL AUTO_INCREMENT,
                                                     `ip` VARCHAR(16) NOT NULL,
    `hostname` VARCHAR(45) NOT NULL,
    `idConectividade` INT,
    `idModelo` INT NOT NULL,
    PRIMARY KEY (`idDispositivo`),
    CONSTRAINT `FK_DISPOSITIVO_CONECTIVIDADE`
    FOREIGN KEY (`idConectividade`)
    REFERENCES `cofre`.`conectividade` (`idConectividade`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
    CONSTRAINT `FK_DISPOSITIVO_MODELO`
    FOREIGN KEY (`idModelo`)
    REFERENCES `cofre`.`modelo` (`idModelo`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cofre`.`credencial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cofre`.`credencial` (
                                                    `idCredencial` INT NOT NULL AUTO_INCREMENT,
                                                    `username` VARCHAR(45) NOT NULL,
    `senha` VARCHAR(45) NOT NULL,
    `idDispositivo` INT NOT NULL,
    PRIMARY KEY (`idCredencial`),
    CONSTRAINT `FK_CREDENCIAL_DISPOSITIVO`
    FOREIGN KEY (`idDispositivo`)
    REFERENCES `cofre`.`dispositivo` (`idDispositivo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cofre`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cofre`.`usuario` (
                                                 `idUsuario` INT NOT NULL,
                                                 `nome` VARCHAR(45) NOT NULL,
    `username` VARCHAR(45) NOT NULL,
    `email` VARCHAR(45) NULL,
    `senha` VARCHAR(45) NOT NULL,
    `idCredencial` JSON NULL,
    PRIMARY KEY (`idUsuario`))
    ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
